version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      SECRET_KEY: secret_key
      DATABASE_URL: sqlite:///site.db
