version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      SECRET_KEY: secret_key
      DATABASE_URL: sqlite:///site.db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:8080"  # Expose Nginx on port 8080 for local access
    depends_on:
      - web
